apiVersion: v1
kind: Service
metadata:
  name: smoke-test-service
spec:
  type: NodePort
  ports:
  - name: http-port
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: smoke-test