version: '3'

services:
  db:
    image: mysql:5.7
    container_name: nandece-db-host
    environment:
      MYSQL_ROOT_PASSWORD: root  # root user password
      MYSQL_DATABASE: nandece_db  # db name created initially
      MYSQL_USER: docker         # user named as docker
      MYSQL_PASSWORD: docker     # password for docker
      MYSQL_TCP_PORT: 3307       # nandece-db port
      TZ: 'Asia/Tokyo'           # timezone seetting in a conainer
    ### setting to make the host paramanent. host_side: container_side
    volumes:
      - ./database/data:/var/lib/mysql               # MySQL data
      - ./database/my.conf:/etc/mysql/conf.d/my.cnf  # MySQL setting file
      - ./database/sql:/docker-entrypoint-initdb.d   # db initialization script
    ### port-forwarding setting
    ### port no. is 3306 as usual but is already used in other system
    ports:
      - 3307:3306
    expose:
      - 3307
    tty: true
    stdin_open: true
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
    

