apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: time-series-analysis
spec:
  schedule: "* 11 * * *"
  #timezone: "Japan/Tokyo"   # Default to local machine timezone
  startingDeadlineSeconds: 0
  concurrencyPolicy: "Replace"      # Default to "Allow"
  successfulJobsHistoryLimit: 4     # Default 3
  failedJobsHistoryLimit: 4         # Default 1
  suspend: false                    # Set to "true" to suspend scheduling
  workflowSpec:
    entrypoint: time-series
    templates:
      - name: time-series
        steps:
        - name: 
        container:
          image: time-series:00.00
          command: [python3, time_series.py, infer-rnn-today]
          args: ["testtest"]
      - name: insert-db
        container:
          image: time-series-db:00.00
          command: [python3, database.py]
          args: [{{time-series}}]