apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: 
      This is a smoke test
spec:
  entrypoint: smoke-test
  templates:
  - name: smoke-test
    inputs: 
      parameters:
        - name: job_id
          value: "001"
    container:
      image: smoke-test:00.00
      command: [python3, smoke_test.py, smoke-test]
      args: ["{{inputs.parameters.job_id}}"]      
